execute_process(COMMAND ${ARTIC_COMMAND} ${TEST_FILE} --emit-llvm -o ${TEST_NAME} RESULT_VARIABLE status)
if (NOT status STREQUAL "0")
    message(FATAL_ERROR "Error when building LLVM module using artic")
endif ()
execute_process(COMMAND ${CLANG_COMMAND} ${TEST_NAME}.ll ${HELPERS_FILE} -o ${CMAKE_SOURCE_DIR}/${TEST_NAME}.run RESULT_VARIABLE status)
if (NOT status STREQUAL "0")
    message(FATAL_ERROR "Error when building executable using clang")
endif ()
execute_process(COMMAND "${CMAKE_SOURCE_DIR}/${TEST_NAME}.run" ${TEST_ARGS} OUTPUT_FILE ${TEST_NAME}.out RESULT_VARIABLE status)
if (NOT status STREQUAL "0")
    message("${CMAKE_SOURCE_DIR}/${TEST_NAME}.run ${TEST_ARGS}")
    message(FATAL_ERROR "Error when running test executable: ${status}")
endif ()
execute_process(COMMAND ${CMAKE_COMMAND} -E compare_files ${TEST_NAME}.out ${TEST_REFERENCE} RESULT_VARIABLE status)
if (NOT status STREQUAL "0")
    message(FATAL_ERROR "Reference does not match test output")
endif ()
