name: build-and-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and test on ${{matrix.os}} in ${{matrix.build-type}} mode
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        repository: AnyDSL/artic
        path: artic

    - uses: actions/checkout@v2
      with:
        repository: AnyDSL/thorin
        path: thorin

    - uses: actions/checkout@v2
      with:
        repository: AnyDSL/half
        path: half

    - name: Configure Thorin
      shell: bash # Necessary because of the $GITHUB_WORKSPACE variable
      run: cmake -S $GITHUB_WORKSPACE/thorin -B ${{runner.workspace}}/thorin/build -DHalf_DIR=$GITHUB_WORKSPACE/half -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build Thorin
      run: cmake --build ${{runner.workspace}}/thorin/build --config ${{matrix.build-type}}
      
    - name: Configure Artic
      shell: bash # Necessary because of the $GITHUB_WORKSPACE variable
      run: cmake -S $GITHUB_WORKSPACE/artic -B ${{runner.workspace}}/artic/build -DThorin_DIR=$GITHUB_WORKSPACE/thorin/build/share/anydsl/cmake -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build Artic
      run: cmake --build ${{runner.workspace}}/artic/build --config ${{matrix.build-type}}

    - name: Test Artic
      working-directory: ${{runner.workspace}}/artic/build
      run: ctest -C ${{matrix.build-type}}
